spring.application.name=bicicletas

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/productos?useSSL=false&serverTimezone=UTC
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/productos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Alej@ndra1604

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Para las llamadas a métodos en el Application.java
#spring.main.web-application-type=none

